import java.util.*;
class Test
{
    public static void main(String args[]){
        
        try{
            
            try{
                int data = 50/0;
            }
            catch(ArithmeticException e){
                System.out.println(e);
            }
            
            try{
                int arr[] = new int[5];
                arr[6] = 600;
            }
            catch(ArrayIndexOutOfBoundsException e){
                System.out.println(e);
            }
            
            try{
                String str = null;
                System.out.println(str.length());
            }
            catch(StringIndexOutOfBoundsException e){
                System.out.println(e);
            }
        }
            catch(Exception e){
                System.out.println(e);
            }
            System.out.println("Exception is not handled");
        
        
    }
}
